openapi: 3.0.0
info:
  title: Meal API
  version: '1.0'
  description: 'Get a meal, get the meal collection, delete a meal, add a meal to the collection.'
servers:
  - url: 'http://localhost:5000'
paths:
  /meal:
    get:
      summary: Get meal collection
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/meal'
      operationId: get-meal
      description: Get meals
      parameters: []
    put:
      summary: Add a meal to the collection
      operationId: put-meal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/meal'
      description: Add a meal to the collection
      parameters:
        - schema: {}
          in: query
          name: mealId
          required: true
  '/meal/{mealId}':
    parameters:
      - schema:
          type: string
        name: mealId
        in: path
        required: true
    get:
      summary: Get a meal
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/meal'
      operationId: get-meal-mealId
      description: Get a meal
      parameters:
        - schema: {}
          in: query
          name: mealId
          required: true
          description: Meal ID
    delete:
      summary: Delete a meal
      operationId: delete-meal-mealId
      responses: {}
      description: Delete a meal
      parameters:
        - schema: {}
          in: query
          name: mealId
          description: Meal ID
          required: true
components:
  schemas:
    meal:
      title: meal
      type: object
      properties:
        mealId:
          type: object
        restaurantId:
          type: object
        mealName:
          type: string
        mealPrice:
          type: number
  securitySchemes:
    API Key:
      name: apikey
      type: apiKey
      in: query
security:
  - API Key: []
