openapi: 3.0.0
info:
  title: Order API
  version: '1.0'
  description: 'Add new order, get an order, get a collection of orders, delete an order, update order status.'
servers:
  - url: 'http://localhost:5000'
paths:
  /order:
    get:
      summary: GetAllOrders
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
      operationId: get-order
      description: Get all the orders in the collection.
      parameters: []
    post:
      summary: AddOrder
      operationId: post-order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
      description: Add an order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order'
  '/order/{orderId}':
    parameters:
      - schema:
          type: string
        name: orderId
        in: path
        required: true
    get:
      summary: Get an order
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
      operationId: get-order-orderId
      description: Get an order.
      parameters:
        - schema: {}
          in: query
          name: orderId
          description: Order ID
          required: true
    put:
      summary: Update an order
      operationId: put-order-orderId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
      description: Update an order.
      parameters:
        - schema: {}
          in: query
          name: orderStatus
          description: Order Status
          required: true
        - schema:
            type: string
          in: query
          name: orderId
          description: Order ID
          required: true
    delete:
      summary: Delete an order
      operationId: delete-order-orderId
      responses:
        '204':
          description: No Content
      description: Delete an order
      parameters:
        - schema: {}
          in: query
          name: orderId
          description: Order ID
          required: true
components:
  schemas:
    order:
      title: Order
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        orderContent:
          type: array
          items:
            $ref: '#/components/schemas/cartItem'
        courierId:
          type: string
        total:
          type: number
    cartItem:
      title: CartItem
      type: object
      properties:
        Meal:
          $ref: ./Meal-API.v1.yaml#/components/schemas/meal
        NumOfMeal:
          type: integer
  securitySchemes:
    API Key:
      name: apikey
      type: apiKey
      in: query
security:
  - API Key - 1: []
