openapi: 3.0.0
info:
  title: Restaurant API
  version: '1.0'
  description: 'Add a restaurant, get a restaurant, delete a restaurant, update a restaurant, make food.'
servers:
  - url: 'http://localhost:5000'
    description: ''
paths:
  /restaurant:
    get:
      summary: GetAllRestaurants
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/restaurant'
      operationId: get-restaurant
      description: Get all restaurants in collections.
      parameters: []
    post:
      summary: AddRestaurant
      operationId: post-restaurant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restaurant'
      description: Add a new restaurant to collection.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/restaurant'
    put:
      summary: UpdateRestaurant
      operationId: put-restaurant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restaurant'
      description: Update a restaurant.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/restaurant'
    delete:
      summary: DeleteRestaurant
      operationId: delete-restaurant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restaurant'
      description: Delete a restaurant.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/restaurant'
  '/restaurant/{:id}':
    parameters:
      - schema:
          type: string
        name: ':id'
        in: path
        required: true
    get:
      summary: GetRestaurantById
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restaurant'
      operationId: get-restaurant-restaurantId
      description: Get a restaurant from the collection by Id
      parameters:
        - schema: {}
          in: query
          name: ':id'
          description: Restaurant ID
          required: true
components:
  schemas:
    restaurant:
      title: restaurant
      type: object
      properties:
        id:
          type: string
        menu:
          type: array
          items:
            type: string
        name:
          type: string
      required:
        - id
        - menu
        - name
  securitySchemes:
    'API Key ':
      name: apikey
      type: apiKey
      in: query
